import { Text } from "@invenio/core";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { serverSideVerificationAndCookieHandeling } from "../../src/utils/functions";

const Home: NextPage = (props) => {
  console.log("props", props);

  return (
    <>
      <Head>
        <title>Home - Invenio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text textVariant="h1" fontSize="xl">
        Home - Invenio
      </Text>
    </>
  );
};

export default Home;
