import { Text } from "@invenio/core";
import type { NextPage } from "next";
import Head from "next/head";

const Numbers: NextPage = () => {
  return (
    <>
      <Head>
        <title>Numbers - Invenio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text textVariant="h1" fontSize="xl">
        Numbers - Invenio
      </Text>
    </>
  );
};

export default Numbers;
