import { Text } from "@invenio/core";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styled, { css } from "styled-components";

import { SignIn } from "../src/organisms/authentication/signIn";
import { SignUp } from "../src/organisms/authentication/signUp";
import { SwitchAuthenticationView } from "../src/organisms/authentication/switchAuthenticationView";
import { device } from "../styles/mediaQueries/mediaQueries";

const TextStyling = css`
  margin-bottom: ${({ theme }) =>
    `${theme.spacings.md}${theme.units.spacings}`};
  @media ${device.tablet} {
    margin-bottom: ${({ theme }) =>
      `${theme.spacings.lg}${theme.units.spacings}`};
  }
`;

const Auth: NextPage = () => {
  const { query } = useRouter();
  const showSignUp = !!query?.signUp;

  return (
    <>
      <Head>
        <title>{`Authentication ${showSignUp ? "sign up" : "sign in"}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text styling={TextStyling} textVariant="h1" fontSize="xl">
        {showSignUp ? "Sign up" : "Sign in"}
      </Text>
      {showSignUp ? <SignUp /> : <SignIn />}
      <SwitchAuthenticationView query={showSignUp ? "signIn" : "signUp"} />
    </>
  );
};

export default Auth;
